# Generated by Django 4.1.3 on 2022-11-19 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apirestappserver", "0002_alter_membership_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_created",
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 19, 20, 6, 44, 25284, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 19, 20, 6, 44, 27283, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 19, 20, 6, 44, 28312, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="updated_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 19, 20, 6, 44, 28312, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 19, 20, 6, 44, 28312, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="updated_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 19, 20, 6, 44, 28312, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usersgroups",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 11, 19, 20, 6, 44, 27283, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
