# Generated by Django 4.1.3 on 2022-12-01 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apirestappserver", "0005_alter_membership_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 1, 22, 17, 39, 190984, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 1, 22, 17, 39, 190984, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="updated_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 1, 22, 17, 39, 190984, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 1, 22, 17, 39, 190984, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="updated_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 1, 22, 17, 39, 190984, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 1, 22, 17, 39, 187986, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usersgroups",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 1, 22, 17, 39, 189985, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
