# Generated by Django 4.1.3 on 2022-12-04 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apirestappserver",
            "0007_usersgroups_image_url_alter_membership_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms",
            name="image_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="membership",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 4, 17, 42, 0, 785014, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 4, 17, 42, 0, 785975, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="updated_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 4, 17, 42, 0, 785975, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 4, 17, 42, 0, 785014, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="updated_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 4, 17, 42, 0, 785975, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 4, 17, 42, 0, 783005, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 4, 17, 42, 0, 783005, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usersgroups",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 4, 17, 42, 0, 784005, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
