# Generated by Django 4.1.3 on 2022-12-10 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apirestappserver", "0015_alter_membership_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 10, 19, 29, 43, 455735, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 10, 19, 29, 43, 456705, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 10, 19, 29, 43, 456705, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 10, 19, 29, 43, 455735, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 10, 19, 29, 43, 455735, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 10, 19, 29, 43, 453735, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 10, 19, 29, 43, 453735, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usersgroups",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 10, 19, 29, 43, 454735, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usersgroups",
            name="image_url",
            field=models.URLField(
                default="https://cdn0.iconfinder.com/data/icons/users-android-l-lollipop-icon-pack/24/group2-512.png"
            ),
        ),
    ]
