# Generated by Django 4.1.3 on 2022-12-11 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apirestappserver", "0016_alter_membership_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 11, 17, 12, 28, 536827, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="created_at",
            field=models.DateTimeField(default="django.utils.timezone.now"),
        ),
        migrations.AlterField(
            model_name="messages",
            name="updated_at",
            field=models.DateTimeField(default="django.utils.timezone.now"),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 11, 17, 12, 28, 536827, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 11, 17, 12, 28, 536827, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="adress",
            field=models.CharField(default="default adress", max_length=300),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 12, 11, 17, 12, 28, 534827, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 11, 17, 12, 28, 534827, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usersgroups",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 11, 17, 12, 28, 535827, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
