# Generated by Django 4.1.3 on 2022-12-11 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apirestappserver", "0019_alter_membership_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 21, 15, 23, 564217)
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="created_at",
            field=models.DateTimeField(default="%2022-%12-%11 %21:%Dic:%23"),
        ),
        migrations.AlterField(
            model_name="messages",
            name="updated_at",
            field=models.DateTimeField(default="%2022-%12-%11 %21:%Dic:%23"),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="created_at",
            field=models.DateTimeField(default="%2022-%12-%11 %21:%Dic:%23"),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="updated_at",
            field=models.DateTimeField(default="%2022-%12-%11 %21:%Dic:%23"),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 11, 21, 15, 23, 561188)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 21, 15, 23, 561188)
            ),
        ),
        migrations.AlterField(
            model_name="usersgroups",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 21, 15, 23, 563217)
            ),
        ),
    ]
