# Generated by Django 4.1.3 on 2022-12-11 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apirestappserver", "0026_alter_membership_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 21, 42, 10, 894233)
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 21, 42, 10, 894233)
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 21, 42, 10, 894233)
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 21, 42, 10, 894233)
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 21, 42, 10, 894233)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 11, 21, 42, 10, 892205)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 21, 42, 10, 892205)
            ),
        ),
        migrations.AlterField(
            model_name="usersgroups",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 11, 21, 42, 10, 893233)
            ),
        ),
    ]
